### ISSUE TITLE
No way to cancel the "How was your experience?" feedback process.

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/orgbook-bc-client-vue#78]
Once you click on one of the thumbs in the "How was your experience?" section of the page there is no way to cancel it without refreshing the page.  The display persists from page to page until you refresh.

![image](https://user-images.githubusercontent.com/10504350/146613272-49f57f04-3a23-4857-bb26-bd0df524e121.png)

![image](https://user-images.githubusercontent.com/10504350/146613283-06654a04-8cf9-4e22-83b1-538e6f622070.png)

**Comment by swcurran** [comment]
@amanji -- I think the fix for this would be an "X Close" button like you added to the Autocomplete dropdown.  Or a "Cancel" button beside the "Submit". 

I think this needs to be at least a "fast follow" on the launch.  It will be tried out by people playing with the interface, and so will generate questions.

Can be before launch if you are comfortable it's not a risky change.

**Comment by WadeBarnes** [comment]
Fixed in `test`
